pcd2pgm_node:
  ros__parameters:
    resolution: 0.1
    min_points_in_pix: 0
    max_points_in_pix: 1
    min_height: -0.1
    max_height: 5.0
    input_pcd: "/home/ryusei/glim_ws/maps/glim_slam.pcd"
    dest_directory: "/home/ryusei/glim_ws/maps/"
    output_pgm_name: "output"
    
